version: '3.8'

services:
  
  frontend:
    container_name: frontend
    image: keepitcoming/placemap-frontend:latest
    build: ./project
    ports:
      - 8080:80
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    depends_on:
      - admin
    links:
      - admin

  admin:
    container_name: admin
    image: keepitcoming/placemap-admin:latest
    build: ./admin
    ports:
      - 4000:3000
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=placemap
      - MYSQL_URL=mysql://root:rootpass@mysqldb:3306/placemap
      - S3_BUCKET_NAME=placemap
      - S3_REGION=us-west-1
      - S3_ACCESS_KEY_ID=AKIAX4HEJQFNDHSX7SQA
      - S3_SECRET_ACCESS_KEY=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
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./.mysql-data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=placemap
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=rootpass

volumes:
  mysqldb: